services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: APP_NAME
    hostname: APP_NAME
    env_file:
      - .env
    ports:
      - '${APP_PORT:-3000}:3000'
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: pnpm-lock.yaml
