FROM node:24-alpine3.23 AS base

RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@latest --activate

# --- SCRIPTS ---
COPY .docker/scripts/install-deps.sh /usr/local/bin/install-deps
COPY .docker/scripts/build-app.sh /usr/local/bin/build-app
COPY .docker/scripts/start-server.sh /usr/local/bin/start-server

RUN chmod +x /usr/local/bin/install-deps \
     /usr/local/bin/build-app \
     /usr/local/bin/start-server

# --- DEPS ---
FROM base AS deps
WORKDIR /app

COPY pnpm-workspace.yaml package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./

RUN install-deps

# --- BUILDER ---
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN build-app

# --- RUNNER ---
FROM base AS runner
WORKDIR /app

ENV NODE_ENV="test"
ENV TZ="America/Sao_Paulo"

RUN apk add --no-cache tzdata \
     && cp /usr/share/zoneinfo/$TZ /etc/localtime \
     && echo $TZ > /etc/timezone

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone/app ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["start-server"]
